[package]
name = "esp32_lora_test"
version = "0.1.0"
authors = ["Priit Laes <plaes@plaes.org>"]
edition = "2021"
license = "MIT"

[dependencies]
defmt = "0.3"

embedded-graphics = "0.8"
embedded-hal = "1"
embedded-hal-async = "1"
embedded-hal-bus = { version = "0.2.0", features = ["async"] }

esp-backtrace = { version = "0.13", features = ["esp32", "defmt", "panic-handler", "exception-handler"] }
esp-hal = { version = "0.19.0", features=["default", "esp32", "defmt", "async", "embedded-hal"]}
esp-hal-embassy = { version = "0.2.0", features=["esp32", "defmt", "integrated-timers"]}
esp-println = { version = "0.9.1", features = ["defmt-espflash", "esp32"] }

static_cell = "2.1.0"

embassy-executor = "0.5.0"
embassy-sync = "0.6.0"
embassy-time = { version = "0.3.2", features = ["defmt", "defmt-timestamp-uptime"]}

lora-phy = { path = "../lora-rs/lora-phy"}
hex-display = "0.3.0"
no_std_strings = "0.1.3"

# TODO: No release with embedded-hal-1 support
ssd1306 = { git = "https://github.com/rust-embedded-community/ssd1306", branch = "master" }

[patch.crates-io]
# TODO: Async SPI with DMA was broken, see https://github.com/esp-rs/esp-hal/issues/1857
esp-hal = { path = "../esp-hal/esp-hal" }
# esp-hal = { git = "https://github.com/esp-rs/esp-hal", rev = "2744a5dd86c0ff3b7a710969f60c7cad67b5539f" }
# TODO: No release for 0.19.0
esp-hal-embassy = { path = "../esp-hal/esp-hal-embassy" }
#esp-hal-embassy = { git = "https://github.com/esp-rs/esp-hal", rev = "2744a5dd86c0ff3b7a710969f60c7cad67b5539f" }

[features]
default = []

[[bin]]
name = "transmit"
path = "src/p2p_transmit.rs"

[[bin]]
name = "receive"
path = "src/p2p_receive.rs"

[[bin]]
name = "spi_test"
path = "src/spi_test.rs"


[[bin]]
name = "gpio_regression"
path = "src/gpio_regression.rs"
