[package]
name = "esp32_lora_test"
version = "0.1.0"
authors = ["Priit Laes <plaes@plaes.org>"]
edition = "2021"
license = "MIT"

[dependencies]
embedded-hal = "1"
embedded-hal-async = "1"

#esp-hal = { path = "../esp-hal/esp-hal", features=["default", "esp32", "defmt", "async", "embedded-hal"]}
esp-hal = { git = "https://github.com/esp-rs/esp-hal", branch = "main", features=["default", "esp32", "defmt", "async", "embedded-hal"]}
# TODO: No release for 0.18.0
#esp-hal-embassy = { path = "../esp-hal/esp-hal-embassy", features=["esp32", "defmt", "integrated-timers"]}
esp-hal-embassy = { git = "https://github.com/esp-rs/esp-hal", branch = "main", features=["esp32", "defmt", "integrated-timers"]}

esp-backtrace = { version = "0.12.1", features = ["esp32", "defmt", "panic-handler", "exception-handler"] }
esp-println = { version = "0.9.1", features = ["defmt-espflash", "esp32"] }

defmt = "0.3.5"

static_cell = "2.1.0"

embedded-graphics = "0.8.1"
# TODO: No release with embedded-hal-1 support
ssd1306 = { git = "https://github.com/rust-embedded-community/ssd1306", branch = "master" }
embassy-executor = "0.5.0"
embassy-time = { version = "0.3.1", features = ["defmt", "defmt-timestamp-uptime"]}
embedded-hal-bus = { version = "0.2.0", features = ["async"] }

lora-phy = { path = "../lora-rs/lora-phy"}

[patch.crates-io]
#esp-hal-embassy = { git = "https://github.com/esp-rs/esp-hal", tag = "v0.18.0" }
#embassy-sync = { git = "https://github.com/embassy-rs/embassy", rev = "64ab23d17d9addd82f0b11a27a3d2219c1a8ec20" }
#embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy", rev = "64ab23d17d9addd82f0b11a27a3d2219c1a8ec20" }
